function renderLiteSettingsPage({
  config,
  page = 1,
  theme = "light",
  conversationStorage = null,
  helpers,
}) {
  const NAME_MAX_LENGTH = 100;
  const PROMPT_BLOCK_MAX_LENGTH = 1000;
  const {
    extractRuntimeSettings,
    renderOptions,
    buildAdminLocation,
    formatDateValue,
    formatBytes,
    renderConfirmOnSubmit,
    withThemeField,
    escapeHtml,
  } = helpers;
  const runtimeSettings = extractRuntimeSettings(config);
  const chatModelValue = runtimeSettings["llm.chat.model"] || config.llm?.chat?.model || config.llm?.chatModel || "";
  const imageModelValue = runtimeSettings["llm.image.model"] || config.llm?.image?.model || config.llm?.imageModel || "";
  const embeddingModelValue = runtimeSettings["llm.embedding.model"] || config.llm?.embedding?.model || config.llm?.embeddingModel || "";
  const transcriptionModelValue = runtimeSettings["llm.transcription.model"] || config.llm?.transcription?.model || config.llm?.transcriptionModel || "";
  const timezoneValue = runtimeSettings["chat.timezone"] || config.chat?.timezone || "UTC";
  const exportLocation = buildAdminLocation({
    path: "/admin/exports/memories",
    theme,
  });
  const appSettingsExportLocation = buildAdminLocation({
    path: "/admin/exports/app-settings",
    theme,
  });
  const conversationEventsExportLocation = buildAdminLocation({
    path: "/admin/exports/conversation-events.csv",
    theme,
  });
  const conversationLogsExportLocation = buildAdminLocation({
    path: "/admin/exports/conversation-logs",
    theme,
  });
  const pruneOptions = renderOptions(["30", "60", "90", "180"], "90");
  const storage = conversationStorage || {
    eventCount: 0,
    messageEventCount: 0,
    oldestEventAt: null,
    newestEventAt: null,
    conversationBytes: 0,
    databaseBytes: 0,
  };

  return [
    "<section class=\"lite-panel settings-form\">",
    "<form method=\"post\" action=\"/admin/actions/settings-save\">",
    withThemeField(theme),
    `<input type="hidden" name="page" value="${escapeHtml(String(page))}">`,
    "<input type=\"hidden\" name=\"view\" value=\"settings\">",
    "<div class=\"copy-block\"><h2>Identity</h2></div>",
    "<div class=\"identity-grid\">",
    `<div><label for="personaName">AI Name</label><input id="personaName" name="personaName" type="text" value="${escapeHtml(runtimeSettings["chat.promptBlocks.personaName"] || "")}" maxlength="${NAME_MAX_LENGTH}"></div>`,
    `<div><label for="userName">User Name</label><input id="userName" name="userName" type="text" value="${escapeHtml(runtimeSettings["chat.promptBlocks.userName"] || "")}" maxlength="${NAME_MAX_LENGTH}"></div>`,
    "</div>",
    "<label for=\"personaProfile\">Voice & Tone</label>",
    "<p class=\"meta\">How your AI should sound in conversation — voice, humour, rhythm, warmth, and language style.</p>",
    `<textarea id="personaProfile" name="personaProfile" maxlength="${PROMPT_BLOCK_MAX_LENGTH}">${escapeHtml(runtimeSettings["chat.promptBlocks.personaProfile"] || "")}</textarea>`,
    `<input type="hidden" name="toneGuidelines" value="${escapeHtml(runtimeSettings["chat.promptBlocks.toneGuidelines"] || "")}">`,
    "<label for=\"userProfile\">About You</label>",
    "<p class=\"meta\">Core facts, preferences, and context your AI should always know about you.</p>",
    `<textarea id="userProfile" name="userProfile" maxlength="${PROMPT_BLOCK_MAX_LENGTH}">${escapeHtml(runtimeSettings["chat.promptBlocks.userProfile"] || "")}</textarea>`,
    "<label for=\"companionPurpose\">How This Space Works</label>",
    "<p class=\"meta\">What kind of relationship, dynamic, or interaction style you want this space to hold.</p>",
    `<textarea id="companionPurpose" name="companionPurpose" maxlength="${PROMPT_BLOCK_MAX_LENGTH}">${escapeHtml(runtimeSettings["chat.promptBlocks.companionPurpose"] || "")}</textarea>`,
    "<label for=\"boundaryRules\">Boundaries</label>",
    "<p class=\"meta\">The lines your AI should not cross, and the rules they should consistently honour.</p>",
    `<textarea id="boundaryRules" name="boundaryRules" maxlength="${PROMPT_BLOCK_MAX_LENGTH}">${escapeHtml(runtimeSettings["chat.promptBlocks.boundaryRules"] || "")}</textarea>`,
    "<label for=\"historyLimit\">Recent Chat Context</label>",
    "<p class=\"meta\">Choose how much recent conversation to include before each reply. More context can improve continuity, but it may increase token usage. (Max 50 messages)</p>",
    `<input id="historyLimit" name="historyLimit" type="number" min="0" max="50" value="${escapeHtml(String(runtimeSettings["chat.historyLimit"] ?? 20))}">`,
    "<label for=\"chatTimezone\">Default Timezone</label>",
    "<p class=\"meta\">Used across Cadence Lite for scheduled automations and other local time cues. Use an IANA timezone like <code>Europe/London</code> or a whole-hour offset like <code>GMT+1</code>.</p>",
    `<input id="chatTimezone" name="chatTimezone" type="text" value="${escapeHtml(timezoneValue)}">`,
    "<div class=\"toolbar\"><button type=\"submit\">Save Settings</button></div>",
    "<div class=\"form-divider\"></div>",
    "<div class=\"copy-block\"><h2>Default Models</h2><p>Set the OpenRouter models Cadence Lite uses for live chat, image analysis, memory retrieval, and transcription. Enter the exact model names you want to use, and make sure your OpenRouter API key is set in Railway variables.</p><p class=\"meta\">When you save changed model slugs, Lite checks them against the models currently available to this OpenRouter key where possible, so filtered-out models are caught earlier.</p></div>",
    "<div class=\"model-table-wrap\">",
    "<table class=\"model-table\">",
    "<thead><tr><th>Function</th><th>Model</th><th>Notes</th></tr></thead>",
    "<tbody>",
    "<tr>",
    "<td data-label=\"Function\"><strong>Chat</strong></td>",
    `<td data-label="Model"><input id="chatModel" name="chatModel" type="text" value="${escapeHtml(chatModelValue)}" placeholder="Enter chat model slug"></td>`,
    "<td class=\"notes\" data-label=\"Notes\">The main conversation model Cadence uses for everyday chat.</td>",
    "</tr>",
    "<tr>",
    "<td data-label=\"Function\"><strong>Images</strong></td>",
    `<td data-label="Model"><input id="imageModel" name="imageModel" type="text" value="${escapeHtml(imageModelValue)}" placeholder="Enter image model slug"></td>`,
    "<td class=\"notes\" data-label=\"Notes\">Used for image input analysis.</td>",
    "</tr>",
    "<tr>",
    "<td data-label=\"Function\"><strong>Embeddings</strong></td>",
    `<td data-label="Model"><input id="embeddingModel" name="embeddingModel" type="text" value="${escapeHtml(embeddingModelValue)}" placeholder="Enter embedding model slug"></td>`,
    "<td class=\"notes\" data-label=\"Notes\">Used for memory search and retrieval. Changing the embeddings model after setup may require rebuilding your memory index.</td>",
    "</tr>",
    "<tr>",
    "<td data-label=\"Function\"><strong>Transcription</strong></td>",
    `<td data-label="Model"><input id="transcriptionModel" name="transcriptionModel" type="text" value="${escapeHtml(transcriptionModelValue)}" placeholder="Enter transcription model slug"></td>`,
    "<td class=\"notes\" data-label=\"Notes\">Used for speech-to-text transcription through OpenRouter. Check your chosen model actually supports audio input.</td>",
    "</tr>",
    "</tbody>",
    "</table>",
    "</div>",
    "<div class=\"toolbar\"><button type=\"submit\">Save Settings</button></div>",
    "</form>",
    "<div class=\"form-divider\"></div>",
    "<div class=\"copy-block\"><h2>Setup &amp; Maintenance</h2><p>Use these tools for the small setup jobs that get Cadence Lite ready for its first conversation.</p></div>",
    "<div class=\"toolbar\" style=\"align-items:center;justify-content:space-between\">",
    "<form method=\"post\" action=\"/admin/actions/register-commands\" style=\"margin:0\">",
    withThemeField(theme),
    "<input type=\"hidden\" name=\"view\" value=\"settings\">",
    `<input type="hidden" name="page" value="${escapeHtml(String(page))}">`,
    "<button type=\"submit\" class=\"toolbar-button secondary\">Register Discord Commands</button>",
    "</form>",
    "<p class=\"meta\" style=\"margin:0;max-width:34rem\">If you are using a fresh Discord bot, run this once after the bot is online so the Lite slash commands appear in your server.</p>",
    "</div>",
    "<div class=\"form-divider\"></div>",
    "<div class=\"copy-block\"><h2>Backup &amp; Restore Memories</h2><p>Import or export your memories as a JSON file. Useful for backups, bulk edits, or moving memories between setups. When you import a file again, existing memories are matched by ID and updated, while new entries with blank IDs are added.</p></div>",
    "<div class=\"toolbar\" style=\"align-items:center\">",
    "<form method=\"post\" action=\"/admin/actions/memory-import\" enctype=\"multipart/form-data\" class=\"toolbar\" style=\"flex:1 1 100%;margin:0\">",
    withThemeField(theme),
    "<input type=\"hidden\" name=\"view\" value=\"settings\">",
    `<input type="hidden" name="page" value="${escapeHtml(String(page))}">`,
    "<div class=\"toolbar-field search\" style=\"max-width:none;flex:1 1 30rem\">",
    "<input type=\"file\" name=\"file\" accept=\"application/json,.json\" required>",
    "</div>",
    "<button type=\"submit\" class=\"toolbar-button secondary\">Import Memories</button>",
    `<a class="toolbar-button secondary" href="${escapeHtml(exportLocation)}">Export Memories</a>`,
    "</form>",
    "</div>",
    "<p class=\"meta\" style=\"margin-top:.75rem\"><em>First-time setup: If you’re starting from scratch, adding one test memory and clicking Resync Memories is enough to create the initial memory index.</em></p>",
    "<div class=\"form-divider\"></div>",
    "<div class=\"copy-block\"><h2>Backup App Settings</h2><p>Download a JSON backup of the rest of your Cadence Lite setup — things like saved settings, schedules, and journals. This does not include durable memories or conversation history.</p></div>",
    "<div class=\"toolbar\" style=\"align-items:center\">",
    `<a class="toolbar-button secondary" href="${escapeHtml(appSettingsExportLocation)}">Export App Settings</a>`,
    "</div>",
    "<p class=\"meta\" style=\"margin-top:.75rem\"><em>This backup is intended as a safety net for upgrades and restores. Durable memories are still exported separately through Export Memories.</em></p>",
    "<div class=\"toolbar\" style=\"align-items:center;justify-content:space-between;margin-top:.75rem\">",
    "<div class=\"copy-block\" style=\"margin:0\"><h2>Rebuild Memory Index</h2><p>Recreate the memory index using your current embeddings model and resync all stored memories from Postgres. Use this if you change the embeddings model, or if the memory index needs to be rebuilt from scratch. This does not delete the source memories stored in Postgres.</p></div>",
    "</div>",
    "<div class=\"toolbar\" style=\"align-items:center;justify-content:space-between\">",
    `<form method="post" action="/admin/actions/memory-rebuild" style="margin:0"${renderConfirmOnSubmit("Rebuild the Qdrant memory index?\n\nThis deletes the current Qdrant collection and recreates it from active durable memories in Postgres using the current embeddings model. Use this after changing the embeddings model or if the index has gone wrong.")}>`,
    withThemeField(theme),
    "<input type=\"hidden\" name=\"view\" value=\"settings\">",
    `<input type="hidden" name="page" value="${escapeHtml(String(page))}">`,
    "<button type=\"submit\" class=\"toolbar-button secondary\">Rebuild Memory Index</button>",
    "</form>",
    "</div>",
    "<div class=\"form-divider\"></div>",
    "<div class=\"copy-block\"><h2>Chat Storage</h2><p>Cadence Lite keeps recent chat history so conversations stay coherent over time. Since older chat isn’t removed automatically, you can review storage here and prune it when needed.</p></div>",
    "<div class=\"model-table-wrap\">",
    "<table class=\"model-table\">",
    "<thead><tr><th>Stored Events</th><th>Message Events</th><th>Oldest</th><th>Newest</th><th>Conversations</th><th>Database</th></tr></thead>",
    "<tbody><tr>",
    `<td data-label="Stored Events">${escapeHtml(String(storage.eventCount || 0))}</td>`,
    `<td data-label="Message Events">${escapeHtml(String(storage.messageEventCount || 0))}</td>`,
    `<td data-label="Oldest">${escapeHtml(formatDateValue(storage.oldestEventAt))}</td>`,
    `<td data-label="Newest">${escapeHtml(formatDateValue(storage.newestEventAt))}</td>`,
    `<td data-label="Conversations">${escapeHtml(formatBytes(storage.conversationBytes))}</td>`,
    `<td data-label="Database">${escapeHtml(formatBytes(storage.databaseBytes))}</td>`,
    "</tr></tbody>",
    "</table>",
    "</div>",
    "<p class=\"meta\" style=\"margin-top:.75rem\"><code>Conversations</code> is the size of Cadence Lite’s stored chat history. <code>Database</code> is the current size of the whole Postgres database. Railway may still report a larger total volume because Postgres itself takes space too.</p>",
    "<div class=\"copy-block\" style=\"margin-top:1rem\"><h2>Prune Old Chat</h2><p>This removes older stored chat to free up space. Newer conversations are kept. It does not delete any messages from Discord, only the saved chat history Cadence Lite keeps in the background.</p></div>",
    "<div class=\"toolbar\" style=\"align-items:end\">",
    `<form method="post" action="/admin/actions/conversation-prune" class="toolbar" style="flex-wrap:wrap;align-items:end;margin:0"${renderConfirmOnSubmit("Prune older conversation history?\n\nThis deletes stored conversation events older than the selected cutoff from Postgres. It won’t touch Discord itself, but Cadence will no longer be able to use those older messages for continuity.")}>`,
    withThemeField(theme),
    "<input type=\"hidden\" name=\"view\" value=\"settings\">",
    `<input type="hidden" name="page" value="${escapeHtml(String(page))}">`,
    "<div class=\"toolbar-field select\">",
    "<label for=\"conversationPruneDays\">Delete stored chat older than</label>",
    `<select id="conversationPruneDays" name="olderThanDays">${pruneOptions}</select>`,
    "</div>",
    "<button type=\"submit\" class=\"toolbar-button secondary\">Prune Old Conversations</button>",
    "</form>",
    "</div>",
    "<div class=\"form-divider\"></div>",
    "<div class=\"copy-block\"><h2>Export Conversations</h2><p>Download stored chat history either as a sortable CSV of conversation events or as a ZIP of readable per-conversation text logs with an index.</p></div>",
    "<div class=\"toolbar\" style=\"align-items:center;gap:.75rem;flex-wrap:wrap\">",
    `<a class="toolbar-button secondary" href="${escapeHtml(conversationEventsExportLocation)}">Export Conversation Events CSV</a>`,
    `<a class="toolbar-button secondary" href="${escapeHtml(conversationLogsExportLocation)}">Export Conversation Logs ZIP</a>`,
    "</div>",
    "<p class=\"meta\" style=\"margin-top:.75rem\"><em>The ZIP export includes one plain-text log per conversation, plus an index CSV and metadata file for bulk review.</em></p>",
    "</section>",
  ].join("");
}

module.exports = {
  renderLiteSettingsPage,
};
